// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.App.Persistencia;

namespace Proyecto.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyecto.App.Dominio.APELLIDOS", b =>
                {
                    b.Property<int>("IdApellidos")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdApellidos");

                    b.ToTable("Apellidos");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.CUENTA", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdCuenta");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCiudad");

                    b.ToTable("NombreCiudad");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.DIRECCION", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoVivienda")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdDireccion");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.DepartamentoPais", b =>
                {
                    b.Property<int>("IdDepartamentoPais")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDepartamento")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("IdPais")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("NombreDepartamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDepartamentoPais");

                    b.ToTable("DepartamentoPais");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.EMAIL", b =>
                {
                    b.Property<int>("CodEmail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodEmail");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.EmailOperador", b =>
                {
                    b.Property<int>("IdEmaOper")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cuenta")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Email")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Operador")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("IdEmaOper");

                    b.ToTable("EmailOperador");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.GENERO", b =>
                {
                    b.Property<int>("IdGENERO")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdGENERO");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.Nombres", b =>
                {
                    b.Property<int>("IdNombre")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdNombre");

                    b.ToTable("Nombre");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.Operador", b =>
                {
                    b.Property<int>("IdCodOperador")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombOperador")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdCodOperador");

                    b.ToTable("Operador");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombrePais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.RH", b =>
                {
                    b.Property<int>("IdRh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("IdRh");

                    b.ToTable("Rh");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.TELEFONO", b =>
                {
                    b.Property<int>("IdTelefon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cuenta")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdTelefon");

                    b.ToTable("Telefono");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.TIPODOCUMENTO", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdTipoDocumento");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuarioDireccion", b =>
                {
                    b.Property<int>("IdUsuarioDireccion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Direccion")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasMaxLength(5)
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioDireccion");

                    b.ToTable("UsuarioDireccion");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuarioFuncionario", b =>
                {
                    b.Property<int>("IdUsuarioArea")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("AreaSucursal")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioArea");

                    b.ToTable("UsuarioFuncionario");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuarioJerarquia", b =>
                {
                    b.Property<int>("IdUsuarioJerarquia")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Jerarquia")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Usuario")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioJerarquia");

                    b.ToTable("UsuarioJerarquia");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuarioTelefono", b =>
                {
                    b.Property<int>("Contador")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Telefono")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Usuario")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Contador");

                    b.ToTable("UsuarioTelefono");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.Usuarios", b =>
                {
                    b.Property<int>("Documento")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Genero")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rh")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumento")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Documento");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuariosApellidos", b =>
                {
                    b.Property<int>("Contador")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Apellidos")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Usuario")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Contador");

                    b.ToTable("UsuariosApellidos");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuariosEmail", b =>
                {
                    b.Property<int>("Conatdor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Actual")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Email")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Fecha")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Usuarios")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Conatdor");

                    b.ToTable("UsuariosEmail");
                });

            modelBuilder.Entity("Proyecto.App.Dominio.UsuariosNombres", b =>
                {
                    b.Property<int>("Contador")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nombres")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Usuario")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Contador");

                    b.ToTable("UsuariosNOmbres");
                });
#pragma warning restore 612, 618
        }
    }
}
